version: '3.5'
services:
#---------------------------------------------------------------------#
#     Kavita - cmx manager
#---------------------------------------------------------------------#
    kavita:
        image: jvmilazz0/kavita:latest    # Using the stable branch from the offical repo.
        container_name: kavita
        volumes:
            - ./NFSRemote/_Comics:/comics            # Manga is just an example you can have the name you want. See the following
            - ./NFSRemote/_Magazines:/riviste          # Use as many as you want
            - ./NFSRemote/_Books:/books            #
            - ./data:/kavita/config     # Change './data if you want to have the config files in a different place.
                                        # /kavita/config must not be changed
        environment:
            - TZ=Europe/Rome
        ports:
            - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
        restart: unless-stopped

#---------------------------------------------------------------------#
#     portainer - gestione container docker
#---------------------------------------------------------------------#
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:latest
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./portainer-data:/data
        ports:
            - 9000:9000

#---------------------------------------------------------------------#
#     Watchtower monitor and update containers images
#---------------------------------------------------------------------#
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower:latest
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 480

#---------------------------------------------------------------------#
#     portainer Agent 
#---------------------------------------------------------------------#
    portainer-agent03:
        container_name: portainer_agent03
        #image: portainer/agent:2.19.4
        image: portainer/agent:latest
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports:
            - 9001:9001

#---------------------------------------------------------------------#
#     Emby
#---------------------------------------------------------------------#
#version: '2.3'

    emby:
        image: lscr.io/linuxserver/emby:latest
        container_name: embyserver
        #runtime: nvidia # Expose NVIDIA GPUs
        #network_mode: host # Enable DLNA and Wake-on-Lan
        environment:
            - $PUID # The UID to run emby as (default: 2)
            - $PGID # The GID to run emby as (default 2)
            #- GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
        volumes:
            - ./emby-data:/config # Configuration directory
            - ./NFSRemoteMedia:/mnt/share1 # Media directory
            #- ./NFSRemoteMedia/mv:/mnt/share2 # Media directory

        ports:
            - 8096:8096 # HTTP port
            - 8920:8920 # HTTPS port
        devices:
            - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
            #- /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
            #- /dev/video10:/dev/video10 #optional
            #- /dev/video11:/dev/video11 #optional
            #- /dev/video12:/dev/video12 #optional
        restart: on-failure