---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Kruuuuuutooo!!
theme: dark
color: zinc
headerStyle: boxed
showStats: true

quicklaunch:
  searchDescriptions: true

background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80 # <----- add this line
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

layout:
  Proxmox:
    #tab: System
    header: true
    useEqualHeights: true
    style: row
    columns: 4
    icon: proxmox.png

  Hypervisor:  
    #tab: System
    header: false
    useEqualHeights: true
    style: row
    columns: 4
    #icon: proxmox.png
  
  Containers:
    #tab: System
    header: true
    useEqualHeights: true
    style: row
    columns: 4
    icon: docker.png
  
  
  Network:
    #tab: System
    header: true
    style: row
    columns: 4

  Network1:
    #tab: System
    header: false
    style: row
    columns: 3
    
  Media/Comm/Storage:
    #tab: System
    header: true
    style: row
    columns: 4
    initiallyCollapsed: true

  Storage:
      #tab: System
      header: true
      #style: row
      #columns: 4
